### ISSUE TITLE
Circle CI Testing and Integration

### ISSUE THREAD

**Issue by adb1042** [Intro-to-SE-lab-Spring-22/Group-8#27]
- [x] Properly integrate Circle CI into the github repository
- [x] Test project with Circle CI, making use of its features

**Comment by school-duy** [comment]
.circleci is in everyone local repo

**Comment by school-duy** [comment]
### CircleCI Test Cases

- [x]  2 for login page
- [x]  2 for register page
- [ ] 2 for add post
- [ ] 2 for friends list
- [ ]  2 for filter

**Comment by school-duy** [comment]
CircleCI is fully implemented now we need to finish up the test cases
