### ISSUE TITLE
CSS and HTML for "userpage.php"

### ISSUE THREAD

**Issue by ryguy1101** [Intro-to-SE-lab-Spring-22/Group-8#47]
Home page css
pls make pretty

**Comment by school-duy** [comment]
1. HTML integration for modals

- [x] Create settings modal
- [x] Create post modal
- [x]  integrate settings modal 
- [x] integrate post modal

2. HTML integration for friends and pending list

- [x] Create friends list
- [x] Create pending list
- [x] integrate friends and pending

**Comment by adb1042** [comment]
The creation of the settings modal, Post modal, Friends list, and Pending list are resolved by #55
